### ISSUE TITLE
Doesn't Work Anymore?

### ISSUE THREAD

**Issue by LilMeatShnak** [Octave13/GHLPokeMachine#10]
From what I've heard and seen; After extracting the zip file there should be an executable file. Well for me there is no such thing. I really don't know what I'm missing here. I looked through the files and none of them are .EXE files. The closest I could get was finding the PNG for the guitar pick icon

**Comment by Octave13** [comment]
You want to go in the release section and dowload 
GHLPokeMachine.zip 
You'll find the .exe file.
Sorry for the delay

**Comment by LilMeatShnak** [comment]
I eventually found it and it works great but if it was a bit easier to find the download then that'd be greatly appreciated. Overall though it fixed my issue 👍🏻
