### ISSUE TITLE
Not connecting anymore

### ISSUE THREAD

**Issue by HappyJuiceLive** [Octave13/GHLPokeMachine#11]
Just says no device detected even though the dongle is connected to my PC and the guitar is connected to the dongle because the P1 light is on...Was working a few months ago with the exact same conditions. gives me no error messages to work with so ig im sol?

**Comment by HappyJuiceLive** [comment]
![Screenshot 2024-08-16 005706](https://github.com/user-attachments/assets/fb211db5-3489-48e0-868a-bb2c1f42d485)

**Comment by HappyJuiceLive** [comment]
![image](https://github.com/user-attachments/assets/78a27f7b-6371-4632-9392-062e38469a61)

**Comment by Octave13** [comment]
You are the only one to have the problem so far. What model of guitar do you use?

**Comment by HappyJuiceLive** [comment]
It's connecting fine on another PC of mine so it seems to be the fault of
some corrupt drivers

**Comment by Octave13** [comment]
Both PC have the same Windows version?

**Comment by HappyJuiceLive** [comment]
Yes, both windows 11 machines.

**Comment by Octave13** [comment]
I'm sorry for your possibly corrupted driver. May I close this issue?

**Comment by HappyJuiceLive** [comment]
Yes!
